-- Generated by Oracle SQL Developer Data Modeler 4.2.0.932
--   at:        2018-05-09 23:29:06 EDT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



CREATE OR REPLACE TYPE campus_typ;
/

CREATE OR REPLACE TYPE faculty_typ;
/

CREATE OR REPLACE TYPE staff_typ;
/

CREATE OR REPLACE TYPE student_typ;
/

CREATE OR REPLACE TYPE degree_typ;
/

CREATE OR REPLACE TYPE building_typ;
/

CREATE OR REPLACE TYPE office_typ;
/

CREATE OR REPLACE TYPE subject_typ;
/

CREATE OR REPLACE TYPE lecturer_typ;
/

CREATE OR REPLACE TYPE person_typ AS OBJECT (
    pers_id           VARCHAR2(50),
    pers_surname      VARCHAR2(50),
    pers_fname        VARCHAR2(50),
    pers_title        VARCHAR2(3),
    pers_address      VARCHAR2(50),
    pers_phone        REAL,
    pers_postcode     REAL,
    campus_location   REF campus_typ
) NOT FINAL NOT INSTANTIABLE;
/

CREATE OR REPLACE TYPE staff_typ UNDER person_typ (
    bld_id       REF building_typ,
    off_no       REF office_typ,
    staff_type   VARCHAR2(10)
) NOT FINAL NOT INSTANTIABLE;
/

CREATE OR REPLACE TYPE comp_skills_typ AS OBJECT (
    skill   VARCHAR2(50)
) FINAL;
/

CREATE OR REPLACE TYPE comp_skills_nt IS
    TABLE OF comp_skills_typ;
/

CREATE OR REPLACE TYPE office_skills_typ AS OBJECT (
    skill   VARCHAR2(50)
) NOT FINAL;
/

CREATE OR REPLACE TYPE office_skills_nt IS
    TABLE OF office_skills_typ;
/

CREATE OR REPLACE TYPE admin_typ UNDER staff_typ (
    admin_title     VARCHAR2(50),
    comp_skills     comp_skills_nt,
    office_skills   office_skills_nt
) NOT FINAL;
/

CREATE OR REPLACE TYPE lecturer_typ UNDER staff_typ (
    area        VARCHAR2(50),
    lect_type   VARCHAR2(50),
    static      procedure displaydetalles
) NOT FINAL NOT INSTANTIABLE;
/

CREATE OR REPLACE TYPE associatelecturer_typ UNDER lecturer_typ (
    no_honours   REAL,
    year_join    REAL
) FINAL;
/

CREATE OR REPLACE TYPE building_typ AS OBJECT (
    bld_id            VARCHAR2(4),
    bld_name          VARCHAR2(50),
    bld_location      VARCHAR2(3),
    bld_level         REAL,
    campus_location   REF campus_typ,
    fac_id            REF faculty_typ,
    static            procedure insertarentabla
) FINAL;
/

CREATE OR REPLACE TYPE campus_typ AS OBJECT (
    campus_location   VARCHAR2(50),
    campus_address    VARCHAR2(50),
    campus_phone      REAL,
    campus_fax        REAL,
    campus_head       REF staff_typ
) FINAL;
/

CREATE OR REPLACE TYPE classroom_typ AS OBJECT (
    bld_id           VARCHAR2(4),
    class_no         VARCHAR2(4),
    class_capacity   REAL
) FINAL;
/

CREATE OR REPLACE TYPE degree_typ AS OBJECT (
    deg_id       VARCHAR2(4),
    deg_name     VARCHAR2(50),
    deg_length   REAL,
    deg_prereq   VARCHAR2(50),
    fac_id       REF faculty_typ,
    static       procedure insertarentabla
) FINAL;
/

CREATE OR REPLACE TYPE dept_prof_nt IS
    TABLE OF lecturer_typ;
/

CREATE OR REPLACE TYPE department_typ AS OBJECT (
    dept_id     VARCHAR2(5),
    dept_name   VARCHAR2(50),
    dept_head   REF staff_typ,
    dept_prof   dept_prof_nt
) FINAL;
/

CREATE OR REPLACE TYPE enrolls_in_typ AS OBJECT (
    student   REF student_typ,
    degree    REF degree_typ
) FINAL;
/

CREATE OR REPLACE TYPE department_nt IS
    TABLE OF department_typ;
/

CREATE OR REPLACE TYPE school_prof_nt IS
    TABLE OF lecturer_typ;
/

CREATE OR REPLACE TYPE school_typ AS OBJECT (
    school_id     VARCHAR2(5),
    school_name   VARCHAR2(50),
    school_head   REF staff_typ,
    school_prof   school_prof_nt
) FINAL;
/

CREATE OR REPLACE TYPE school_nt IS
    TABLE OF school_typ;
/

CREATE OR REPLACE TYPE rc_units_typ AS OBJECT (
    unit   VARCHAR2(50)
) FINAL;
/

CREATE OR REPLACE TYPE rc_unit_nt IS
    TABLE OF rc_units_typ;
/

CREATE OR REPLACE TYPE research_center_typ AS OBJECT (
    rc_id     VARCHAR2(5),
    rc_name   VARCHAR2(50),
    rc_head   REF staff_typ,
    rc_unit   rc_unit_nt
) FINAL;
/

CREATE OR REPLACE TYPE research_center_nt IS
    TABLE OF research_center_typ;
/

CREATE OR REPLACE TYPE faculty_typ AS OBJECT (
    fac_id            REAL,
    fac_name          VARCHAR2(50),
    fac_dean          REF staff_typ,
    department        department_nt,
    school            school_nt,
    research_center   research_center_nt,
    static            procedure displayencargados
) FINAL;
/

CREATE OR REPLACE TYPE lab_equipment_typ AS OBJECT (
    equipment   VARCHAR2(50)
) FINAL;
/

CREATE OR REPLACE TYPE lab_equipment_nt IS
    TABLE OF lab_equipment_typ;
/

CREATE OR REPLACE TYPE lab_typ AS OBJECT (
    bld_id          VARCHAR2(4),
    lab_no          VARCHAR2(5),
    lab_capacity    REAL,
    lab_equipment   lab_equipment_nt
) FINAL;
/

CREATE OR REPLACE TYPE office_typ AS OBJECT (
    bld_id      VARCHAR2(4),
    off_no      VARCHAR2(5),
    off_phone   REAL,
    static      procedure displayocupantes
) FINAL;
/

CREATE OR REPLACE TYPE seniorlecturer_typ UNDER lecturer_typ (
    no_phd       REAL,
    no_master    REAL,
    no_honours   REAL
) FINAL;
/

CREATE OR REPLACE TYPE student_typ UNDER person_typ (
    year   REAL
) NOT FINAL;
/

CREATE OR REPLACE TYPE subject_typ AS OBJECT (
    subj_id            VARCHAR2(50),
    subj_name          VARCHAR2(50),
    subj_credit        REAL,
    subj_prereq        REF subject_typ,
    lecturer           REF lecturer_typ,
    subj_description   VARCHAR2(100)
) FINAL;
/

CREATE OR REPLACE TYPE takes_typ AS OBJECT (
    student   REF student_typ,
    subject   REF subject_typ,
    marks     NUMBER
) FINAL;
/

CREATE OR REPLACE TYPE tech_skills_typ AS OBJECT (
    skill   VARCHAR2(50)
) FINAL;
/

CREATE OR REPLACE TYPE tech_skills_nt IS
    TABLE OF tech_skills_typ;
/

CREATE OR REPLACE TYPE technician_typ UNDER staff_typ (
    tech_title    VARCHAR2(50),
    tech_skills   tech_skills_nt
) FINAL;
/

CREATE OR REPLACE TYPE tutor_typ AS OBJECT (
    no_hours   REAL,
    rate       FLOAT(2),
    staff      REF staff_typ,
    student    REF student_typ
) FINAL;
/

CREATE CLUSTER building_cluster ( bld_id VARCHAR(4) )
    SIZE 512
    NOPARALLEL
NOROWDEPENDENCIES NOCACHE;

CREATE INDEX idx_building_cluster ON CLUSTER building_cluster NOCOMPRESS
    NOPARALLEL;

CREATE TABLE admin OF admin_typ
    NESTED TABLE comp_skills STORE AS comp_skills NESTED TABLE office_skills STORE AS office_skills;

CREATE TABLE associatelecturer OF associatelecturer_typ;

CREATE TABLE building OF building_typ
    CLUSTER building_cluster ( bld_id );

CREATE TABLE campus OF campus_typ;

CREATE TABLE classroom OF classroom_typ
    CLUSTER building_cluster ( bld_id );

CREATE TABLE degree OF degree_typ;

CREATE TABLE enrolls_in OF enrolls_in_typ;

CREATE TABLE faculty OF faculty_typ
    NESTED TABLE department STORE AS department (
        NESTED TABLE dept_prof STORE AS dept_prof
    ) NESTED TABLE school STORE AS school (
        NESTED TABLE school_prof STORE AS school_prof
    ) NESTED TABLE research_center STORE AS research_center (
        NESTED TABLE rc_unit STORE AS rc_unit
    );

CREATE TABLE lab OF lab_typ
    CLUSTER building_cluster ( bld_id )
    NESTED TABLE lab_equipment STORE AS lab_equipment;

CREATE TABLE office OF office_typ
    CLUSTER building_cluster ( bld_id );

CREATE TABLE seniorlecturer OF seniorlecturer_typ;

CREATE TABLE student OF student_typ;

CREATE TABLE subject OF subject_typ;

CREATE TABLE takes OF takes_typ;

CREATE TABLE technician OF technician_typ
    NESTED TABLE tech_skills STORE AS tech_skills;

CREATE TABLE tutor OF tutor_typ;

CREATE OR REPLACE TYPE BODY lecturer_typ AS
    STATIC PROCEDURE displaydetalles
        AS 
    -- Empty PL/SQL Body 
    BEGIN
        NULL;
    END;

END;
/

CREATE OR REPLACE TYPE BODY building_typ AS
    STATIC PROCEDURE insertarentabla
        AS 
    -- Empty PL/SQL Body 
    BEGIN
        NULL;
    END;

END;
/

CREATE OR REPLACE TYPE BODY degree_typ AS
    STATIC PROCEDURE insertarentabla
        AS 
    -- Empty PL/SQL Body 
    BEGIN
        NULL;
    END;

END;
/

CREATE OR REPLACE TYPE BODY faculty_typ AS
    STATIC PROCEDURE displayencargados
        AS 
    -- Empty PL/SQL Body 
    BEGIN
        NULL;
    END;

END;
/

CREATE OR REPLACE TYPE BODY office_typ AS
    STATIC PROCEDURE displayocupantes
        AS 
    -- Empty PL/SQL Body 
    BEGIN
        NULL;
    END;

END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             1
-- ALTER TABLE                              0
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                  10
-- CREATE STRUCTURED TYPE                  27
-- CREATE STRUCTURED TYPE BODY              5
-- CREATE CLUSTER                           1
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
